logging:
    file: logs/mod-data-extractor.log
    level:
      org:
        folio.rest: INFO
        hibernate: INFO
        springframework:
          security: INFO
          web: INFO

server:
    port: 9000

spring:
    data.rest:
        returnBodyOnCreate: true
        returnBodyOnUpdate: true
    datasource:
        platform: h2
        url: jdbc:h2:./target/mod-data-extractor;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        # platform: postgres
        # driverClassName: org.postgresql.Driver
        # url: jdbc:postgresql://localhost:5432/mod-data-extractor
    
        username: folio
        password: folio
h2:
    console:
        enabled: true
        path: /h2console
    jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect