logging:
  file: logs/mod-spine-o-matic.log
  level:
    org:
      tamu.modspineomatic: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO

server:
  port: 80

okapi:
  url: https://folio-okapi-q2.library.tamu.edu
  credentials:
    username: tamu_admin
    password: admin
  tenant: tamu

spring:
  thymeleaf:
      suffix: .xml
      templateMode: XML
      cacheable: false
  datasource:
    platform: h2
    url: jdbc:h2:./target/mod-spine-o-matic;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    # platform: postgres
    # driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/mod-spine-o-matic

    username: folio
    password: folio
h2:
  console:
    enabled: true
    path: /h2console
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  # database-platform: org.hibernate.dialect.PostgreSQLDialect
